# Usa uma imagem oficial do Node.js (versão leve)
FROM node:22-alpine

# Cria a pasta de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos de dependência primeiro (otimiza o cache do Docker)
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o resto do código do seu computador para dentro do container
COPY . .

# Gera o Prisma Client (Passo obrigatório se estiver usando Prisma)
RUN npx prisma generate

# Expõe a porta que o Express/Fastify vai rodar
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "run", "dev"]